document.writeln("<header>");
document.writeln("	<div class=\"header-top\">");
document.writeln("		<div>");
document.writeln("			<img src=\"../img/Logo.png\" alt=\"\">");
document.writeln("			<h3>淼溪信息科技</h3>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\"header-bottom\"></div>");
document.writeln("	<div class=\"ulBox\">");
document.writeln("		<ul class=\"listItems\">");
document.writeln("			<li><a href=\"index.html\">首页</a></li>");
document.writeln("			<li><a href=\"aboutMaxi.html\">关于淼溪</a></li>");
document.writeln("			<li><a href=\"product.html\">公司产业</a></li>");
document.writeln("			<li><a href=\"News.html\">新闻资讯</a></li>");
document.writeln("			<li><a href=\"contact.html\">联系我们</a></li>");
document.writeln("			<li><a href=\"join.html\">招商加盟</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</header>");